const kahani = [
  "I wrote this ❤️",
  "Why it is so hard to find a partner?",
  "See what's happening here..",
  "One person will ask questions and the other will answer",
  "and due to one-sided communication, it will not create interest",
  "And they will stop messaging and move to the next one..",
  "Interest dono side se hona chaiye.. starting se hi",
  "Yaha toh ye job dundhne se bhi tough ho gya hai",
  "Agar soche toh we are not bad peoples",
  "We can be a good partner",
  "But still we are single",
  "Why?",
  "Don't you want someone in your life?",
  "who will pamper you",
  "who will take care of you",
  "who will listen to all your nonsense",
  "And inside we know we are that partner",
  "just scared to show ourselves",
  "Oh, I forgot to introduce myself",
  "I am a software developer",
  "I am a poet",
  "I am a good listener",
  "I am a good partner",
  "I am a little childish",
  "I want to cherish life",
  "shaadi ke baad hum job se thak ke ghar aaye toh",
  "kisi ke paas koi duty nahi honi chaiye..",
  "ki ab khana banana hai ya kuch aur",
  "Wo sab ke liye we will have a cook",
  "hum bas chill karenge",
  "We will have our tv series jo saath dekhenge",
  "Weekends par jaane k liye cafes dundhenge",
  "Trips plan karenge",
  "Hug karke soyenge",
  "Chinatao se door ho jayenge",
  "sahi hai na?",
  "If you agree with me",
  "Then why don't you message me?",
  "Let's talk and see if we can be a good partner for each other",
];

  export default kahani